# <center> Array

In [1]:
import numpy as np

#### 1 Dimensional array

In [2]:
a = np.array([2,3,54,7,25])
a

array([ 2,  3, 54,  7, 25])

#### Attributes of array

In [3]:
# to check the type
a.dtype

dtype('int32')

In [4]:
# to check the shape
a.shape

(5,)

In [5]:
# to check the dimension
a.ndim

1

In [6]:
# to check the size
a.size

5

In [7]:
# to find the value corresponding to the index number
a[0]

2

#### Multidimenional array

In [8]:
a_2D = np.array([[1,2,3,45,5],[2,5,8,9,5]])
a_2D

array([[ 1,  2,  3, 45,  5],
       [ 2,  5,  8,  9,  5]])

In [9]:
a_2D.ndim

2

In [10]:
a_2D.shape

(2, 5)

In [11]:
a_2D.size

10

In [12]:
# to obtain second element in first row
a_2D[0][2]

3

In [13]:
# to obtain fourth element in second row
a_2D[1][3]

9

#### Another type of multi dimensional array

In [14]:
b = np.array([[[[2,4,5,7],[2,3,4,5]]]])
b

array([[[[2, 4, 5, 7],
         [2, 3, 4, 5]]]])

In [15]:
b.ndim

4

In [16]:
b.shape

(1, 1, 2, 4)

In [17]:
b.size

8

In [18]:
b[0][0][0][1]

4

In [19]:
b[0][0][1][1]

3

#### Big array

In [20]:
a_D = np.array([
[
[1,2,3,4,5,6]
],
[
[2,3,4,5,6,5]
],
[
[2,5,6,6,5,6]
]
],dtype=float)

In [21]:
a_D

array([[[1., 2., 3., 4., 5., 6.]],

       [[2., 3., 4., 5., 6., 5.]],

       [[2., 5., 6., 6., 5., 6.]]])

In [22]:
a_D.ndim

3

In [23]:
a_D.shape

(3, 1, 6)

In [24]:
np.set_printoptions(suppress=True)

In [25]:
b_D = np.array([
[
[1,2,3,5],[1,5,6,3],[15,65,74,6]
],
[
[48,55,652,5563],[2,654,63,53],[45,5,6,1]
]
],dtype=float)
b_D

array([[[   1.,    2.,    3.,    5.],
        [   1.,    5.,    6.,    3.],
        [  15.,   65.,   74.,    6.]],

       [[  48.,   55.,  652., 5563.],
        [   2.,  654.,   63.,   53.],
        [  45.,    5.,    6.,    1.]]])

In [26]:
b_D.ndim

3

In [27]:
b_D.shape

(2, 3, 4)

#### Filling arrays

In [28]:
# to fill a certain number by which shape and the number to be fill is already mentioned.
a_full = np.full((3,2,3),5)
a_full

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [29]:
full=np.full((3,4,4),5)
full

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [30]:
# here the array is full of zero for a specified dimension,row and column
a_zero = np.zeros((3,4,5))
a_zero

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [31]:
a_ones = np.ones((3,4,5))
a_ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### Empty and random 

In [32]:
empty = np.empty((3,2))
empty

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
random = np.random.random((3,3,4))
random

array([[[0.38153893, 0.43977228, 0.95894912, 0.25997725],
        [0.82152736, 0.66146437, 0.00917159, 0.02291781],
        [0.99466373, 0.66023709, 0.84780767, 0.66585883]],

       [[0.208141  , 0.88146654, 0.7551307 , 0.39806214],
        [0.32656947, 0.82147556, 0.40841155, 0.64889164],
        [0.97333684, 0.73705289, 0.9343921 , 0.95773719]],

       [[0.51421888, 0.02913113, 0.1628235 , 0.48886388],
        [0.00055967, 0.60728947, 0.09423565, 0.55278038],
        [0.73841765, 0.37455158, 0.59246515, 0.6089062 ]]])

In [34]:
random.ndim

3

#### Ranges

In [35]:
# Instead of filling the same values we can create sequences of values by specifying the boundaries.For this we use two functions,namely namely and linscape.
a_range = np.arange(0,50,8)
a_range

array([ 0,  8, 16, 24, 32, 40, 48])

In [36]:
b_range = np.arange(10,15,2.2)
b_range

array([10. , 12.2, 14.4])

In [37]:
b_range.ndim

1

In [38]:
a_linspace = np.linspace(0,50,5)
a_linspace

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [39]:
np.arange(10, 111,20)

array([ 10,  30,  50,  70,  90, 110])

In [40]:
np.random.randint(0, 50, 25)

array([44, 43,  7, 25, 46,  4, 13,  5,  9, 40, 35,  9, 17, 19, 20, 21, 18,
       22, 26, 23,  1, 39, 20, 25, 27])

In [41]:
np.random.rand(10)

array([0.21961075, 0.48642997, 0.02657549, 0.60675016, 0.00985582,
       0.25774095, 0.90626846, 0.49764191, 0.79794987, 0.67055019])

#### Math functions

In [42]:
r = np.random.random((3,3,4))
r

array([[[0.79409564, 0.5887583 , 0.13687678, 0.39480043],
        [0.91788076, 0.05900229, 0.82807758, 0.43105247],
        [0.03871859, 0.1970956 , 0.59798073, 0.79041572]],

       [[0.78998755, 0.38300601, 0.74845573, 0.049379  ],
        [0.52702461, 0.54839287, 0.66419217, 0.28710357],
        [0.07297901, 0.85586927, 0.57138254, 0.89160126]],

       [[0.8416422 , 0.32689418, 0.90253526, 0.22347807],
        [0.73811685, 0.65764282, 0.73364079, 0.96443823],
        [0.2044097 , 0.04806092, 0.40165311, 0.55035107]]])

In [43]:
# taking power of each values
np.exp(r)

array([[[2.21243925, 1.80174979, 1.14668684, 1.48408798],
        [2.50397824, 1.06077767, 2.28891426, 1.5388763 ],
        [1.03947792, 1.21786046, 1.81844317, 2.20431262]],

       [[2.203369  , 1.46668685, 2.11373332, 1.05061846],
        [1.69388484, 1.73046969, 1.94292033, 1.33256222],
        [1.07570796, 2.35341924, 1.77071343, 2.43903204]],

       [[2.32017405, 1.38665474, 2.46584674, 1.25041822],
        [2.09199227, 1.93023705, 2.08264932, 2.62331353],
        [1.22680068, 1.04923457, 1.49429289, 1.73386162]]])

In [44]:
# taking sin value of each elenment
np.sin(r)

array([[[0.71323   , 0.55532881, 0.13644978, 0.38462398],
        [0.79431596, 0.05896806, 0.73663261, 0.41782723],
        [0.03870892, 0.19582199, 0.56297475, 0.71064582]],

       [[0.71034451, 0.37371037, 0.68050802, 0.04935894],
        [0.50296392, 0.52131644, 0.61642323, 0.28317554],
        [0.07291425, 0.75514106, 0.54079549, 0.7780786 ]],

       [[0.74573822, 0.32110324, 0.78490033, 0.22162254],
        [0.67289607, 0.611253  , 0.66957824, 0.8217289 ],
        [0.20298919, 0.04804242, 0.39094043, 0.52298649]]])

In [45]:
#taking cosine value of each elenment
np.cos(r)

array([[[0.70093007, 0.83163087, 0.99064699, 0.92307334],
        [0.60750486, 0.99825987, 0.67629312, 0.9085265 ],
        [0.99925053, 0.98063946, 0.82647409, 0.70354994]],

       [[0.70385416, 0.92754545, 0.73274063, 0.9987811 ],
        [0.86430741, 0.85336345, 0.78741501, 0.95906809],
        [0.99733821, 0.65556234, 0.84115411, 0.62816693]],

       [[0.66623907, 0.9470442 , 0.61962204, 0.97513253],
        [0.73973703, 0.79143526, 0.74274153, 0.56987859],
        [0.97918098, 0.9988453 , 0.92041598, 0.85234097]]])

In [46]:
# taking tan  value of each elenment
np.tan(r)

array([[[1.01754802, 0.66775877, 0.13773804, 0.41667759],
        [1.30750552, 0.05907086, 1.08922091, 0.45989548],
        [0.03873795, 0.19968806, 0.68117653, 1.01008581]],

       [[1.00922116, 0.40290248, 0.9287161 , 0.04941917],
        [0.58192712, 0.61089614, 0.78284415, 0.29526115],
        [0.07310885, 1.15189817, 0.64292082, 1.23864942]],

       [[1.11932526, 0.33905834, 1.2667405 , 0.22727427],
        [0.90964226, 0.7723348 , 0.90149561, 1.44193678],
        [0.20730508, 0.04809796, 0.4247432 , 0.61358835]]])

In [47]:
# taking log value of each elenment
np.log(r)

array([[[-0.23055137, -0.52973954, -1.98867418, -0.92937488],
        [-0.08568778, -2.83017899, -0.18864843, -0.84152545],
        [-3.25143543, -1.6240664 , -0.51419674, -0.23519624]],

       [[-0.23573809, -0.95970459, -0.28974322, -3.00823001],
        [-0.64050803, -0.60076334, -0.40918377, -1.24791225],
        [-2.6175834 , -0.15563764, -0.55969635, -0.11473627]],

       [[-0.17240029, -1.11811876, -0.10254753, -1.49844199],
        [-0.30365313, -0.41909332, -0.30973575, -0.0362095 ],
        [-1.58762895, -3.03528594, -0.91216646, -0.5971989 ]]])

In [48]:
# taking square root of each elenment
np.sqrt(r)

array([[[0.89112044, 0.76730587, 0.36996862, 0.62833146],
        [0.95806094, 0.24290387, 0.90998768, 0.65654587],
        [0.1967704 , 0.4439545 , 0.77329214, 0.88905327]],

       [[0.88881244, 0.6188748 , 0.86513336, 0.22221387],
        [0.72596461, 0.74053553, 0.81497986, 0.53582047],
        [0.27014628, 0.92513203, 0.7558985 , 0.9442464 ]],

       [[0.9174106 , 0.57174661, 0.95001856, 0.47273467],
        [0.85913727, 0.8109518 , 0.85652834, 0.98205816],
        [0.45211691, 0.21922801, 0.63376109, 0.7418565 ]]])

#### Aggregate functions

In [49]:
# Returns the sum of all values in the array
r.sum()

18.75699168669748

In [50]:
# Returns the minimum values in the array
r.min()

0.038718590133849706

In [51]:
# Returns the arithmetic mean of all values in the array
r.mean()

0.5210275468527077

In [52]:
# Returns the median of all values in the array
np.median(r)

0.5608668022930028

In [53]:
# Returns the standard deviation of values in the array
np.std(r)

0.29095445273513443